# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        # the name of the "filter set"
        admin_preview :
            quality : 85
            filters :
                scale:
                    dim: [ 600, 600 ]
        admin_thumbnail_square:
            filters:
                thumbnail:
                    size:          [150, 150]
                    mode:          outbound
                    allow_upscale: true
        site_image_medium :
            quality : 85
            filters :
                scale : 
                    dim: [ 800, 800 ]
        site_gallery_preview :
            quality : 85
            filters :
                crop :
                    size: [ 768, 432 ]
                    start: [0, 0]
                scale:
                    dim: [ 768, 432 ]
        site_user_square :
            quality : 85
            filters :
                crop:
                    size: [ 500, 500 ]
                    start: [ 050, 050 ]
                scale:
                    dim: [ 500, 500 ]
                grayscale: ~
