framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'info@zinnechoeur.be'
            recipients: ['freddgeorge@gmail.com']
        headers:
            From: 'Info <info@zinnechoeur.be>'
